// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDuomAq_a4S_flSOKeNyIsiFZVgFVk7LA',
    appId: '1:1066971051364:web:ba786b95917a65ec073671',
    messagingSenderId: '1066971051364',
    projectId: 'blood-donation-8367a',
    authDomain: 'blood-donation-8367a.firebaseapp.com',
    databaseURL: 'https://blood-donation-8367a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blood-donation-8367a.firebasestorage.app',
    measurementId: 'G-0B7DWSQ8KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPwsB5Uaf5X0I2pHALPrUb4qTvCYZdK18',
    appId: '1:1066971051364:android:bce746237e6dd4ee073671',
    messagingSenderId: '1066971051364',
    projectId: 'blood-donation-8367a',
    databaseURL: 'https://blood-donation-8367a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blood-donation-8367a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiCUjrVOzqnzwSCnFDPDhjkmzKbWkJMgE',
    appId: '1:1066971051364:ios:502be37989d8780c073671',
    messagingSenderId: '1066971051364',
    projectId: 'blood-donation-8367a',
    databaseURL: 'https://blood-donation-8367a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blood-donation-8367a.firebasestorage.app',
    iosClientId: '1066971051364-ojje3rg0cu0i8gbis8o92uibusegeneo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiCUjrVOzqnzwSCnFDPDhjkmzKbWkJMgE',
    appId: '1:1066971051364:ios:502be37989d8780c073671',
    messagingSenderId: '1066971051364',
    projectId: 'blood-donation-8367a',
    databaseURL: 'https://blood-donation-8367a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blood-donation-8367a.firebasestorage.app',
    iosClientId: '1066971051364-ojje3rg0cu0i8gbis8o92uibusegeneo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDuomAq_a4S_flSOKeNyIsiFZVgFVk7LA',
    appId: '1:1066971051364:web:d044b36a11e5088f073671',
    messagingSenderId: '1066971051364',
    projectId: 'blood-donation-8367a',
    authDomain: 'blood-donation-8367a.firebaseapp.com',
    databaseURL: 'https://blood-donation-8367a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blood-donation-8367a.firebasestorage.app',
    measurementId: 'G-L9SS62411Z',
  );

}